Encoding:
  Enabled: false

TrailingWhitespace:
  Enabled: true
  
DefWithParentheses:
  Enabled: true

DefWithoutParentheses:
  Enabled: true

LineLength:
  Enabled: false

Documentation:
  Enabled: false

# There is a subtle difference between blocks with {...} and do...end.
# Rubocop does not seem to notice that.
Blocks:
  Enabled: true

LeadingCommentSpace:
  Enabled: true

MethodLength:
  Enabled: false

CaseEquality:
  Enabled: true

StringLiterals:
  Enabled: true

SpaceInsideHashLiteralBraces:
  Enabled: true

Loop:
  Enabled: false

CollectionMethods:
  Enabled: false

RedundantReturn:
  Enabled: true

CommentAnnotation:
  Enabled: false

AssignmentInCondition:
  Enabled: true

SignalException:
  Enabled: false

RegexpLiteral:
  Enabled: false
